id: bash_script
learningObjectives: 
- Writing bash scripts
hints:
- In order to allow someone else to use your script you would want to make it exectutable. You can find instructions here [link](https://www.andrewcbancroft.com/blog/musings/make-bash-script-executable/)
- To get arguments in your bash script you can use the following [link](https://www.baeldung.com/linux/use-command-line-arguments-in-bash-script)
- To create archives using tar. You can find instructions here [link](https://linuxize.com/post/how-to-create-and-extract-archives-using-the-tar-command-in-linux/) 
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "As I said before, this is part of a bigger investigation so we need to archive and back up the log file for the auditors."
        delay: 1300      
      - text: :instruction[Could you please create a script that takes the log file as an argument and backs it up in an archive called `backup.tar.gz` in the root directory.]
        delay: 1300
      - text: :instruction[Name the script,`backup.sh` and put it under the scripts directory in the backend directory]
        delay: 1300
      - text: "Make sure the script is executable"
        delay: 1300
      - text: :instruction[Open a PR when you're done]
        delay: 1300

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: ${eventType}
      cases:
        github_pr_opened:
          do:      
          - actionId: github_pr_comment
            params:
              person: keen
              message: You made a PR. Let me review it quickly.
              
        github_pr_workflow_complete_success:
          do:
          - actionId: github_pr_approve
            params:
              person: keen
              message: Amazing! We'll use this script to create backups for the rest of the log files.
              
        github_pr_workflow_complete_failure:
          do:
          - actionId: github_pr_reject
            params:
              person: keen
              message: "Please make sure the name of the backup file is `backup.tar.gz` and it's in the root directory"

        github_pr_merged:
          do:
          - actionId: finish_step


githubActions:
  backend:
    testFile: "check.js"
    cmd: "bash ${testFile}"
