id: bash_script
learningObjectives: 
- Writing bash scripts
hints:
- In order to allow someone else to use your script you would want to make it exectutable. You can find instructions here [link](https://www.andrewcbancroft.com/blog/musings/make-bash-script-executable/)
- To get arguments in your bash script you can use the following [link](https://www.baeldung.com/linux/use-command-line-arguments-in-bash-script)
- To create archives using tar. You can find instructions here [link](https://linuxize.com/post/how-to-create-and-extract-archives-using-the-tar-command-in-linux/) 
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
        delay: 1000
      - text: "The investigation is still on going, so we need to keep the log. There might be more log files coming, we'll need to keep those too."
        delay: 1300
      - text: "Since more logs are coming, it's best to create a script that backups up the logs."
        delay: 1300      
      - text: :instruction[Could you please create a script that takes the log file as an argument and generates an archive called `backup.tar.gz` in the root directory.]
        delay: 1300
      - text: :instruction[Name the script,`backup.sh` and put it under the scripts directory in the backend directory]
        delay: 1300
      - text: "Make sure the script is executable"
        delay: 1300
      - text: :instruction[Open a PR when you're done]
        delay: 1300

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: ${eventType}
      cases:
        github_pr_opened:
          do:      
          - actionId: github_pr_comment
            params:
              person: keen
              message: Lovely. Let me take a look.
              
        github_pr_workflow_complete_success:
          do:
          - actionId: github_pr_approve
            params:
              person: keen
              message: Amazing, that will save us (meaning you) tons of work.
              
        github_pr_workflow_complete_failure:
          do:
          - actionId: github_pr_reject
            params:
              person: keen
              message: "Umm, something is not quite right, please make sure your output is in the following format: `first name` `last name`."

        github_pr_merged:
          do:
          - actionId: finish_step


githubActions:
  backend:
    testFile: "check.js"
    cmd: "bash ${testFile}"
