id: bash_filter
learningObjectives: 
- Learn at least one bash command that can search for a specific string in a file
hints:
- Search for strings in file with Linux commands
startFlow: 
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Hi ${user.firstName}. This was something that was supposed to be done ny Navi considering the nature of the investigation."
        delay: 1000
      - text: "But you know how Navi gets when he is on vacation."
        delay: 1000
  - actionId: bot_message
    params:
      person: lucca
      messages:
      - text: "![](https://media.giphy.com/media/CoDp6NnSmItoY/giphy.gif)" 
        delay: 1000
      - text: "He doesn't answer emails or calls"
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "So I guess it's just you."
        delay: 1000
      - text: "Well, this is part of a bigger investigation. There's a hacker who we suspect got into our system. Here is the log [file](https://drive.google.com/file/d/165p52gmI8TR0Tl-v9c3IawVNRnYvERpt/view?usp=sharing)"
        delay: 1000
      - text: "Could you check in the log file and find out how many users accessed the system on 16 June?"

trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
          - "2"
          - "Two"
          - "two"
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Thanks mate. That was quick." 
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Are you sure? This doesn't make sense..."
              delay: 2500
