id: bash_script
learningObjectives: 
- Writing bash scripts
hints:
- In order to allow someone else to use your script you would want to make it exectutable. You can find instructions here [link](https://www.andrewcbancroft.com/blog/musings/make-bash-script-executable/)
- To get arguments in your bash script you can use the following [link](https://www.baeldung.com/linux/use-command-line-arguments-in-bash-script)
- To create archives using tar. You can find instructions here [link](https://linuxize.com/post/how-to-create-and-extract-archives-using-the-tar-command-in-linux/) 
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "One last thing, just quickly create a script to create log bckups. We might need this log in the future and the script will come in handy, more logs are coming."
        delay: 1300
      - text: "Please create a new script under the scripts directory in the backend directory called `backup.sh` (and make sure you have the permission to run it)"
        delay: 1300
      - text: "The script should take in a file as an argument and generate an archive in the root directory."
        delay: 1300
      - text: "I remember Navi said he uses tar and gzip. He said it's the standard around here."
        delay: 1300
      - text: "Open a PR when you're done."
        delay: 1300

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: ${eventType}
      cases:
        github_pr_opened:
          do:      
          - actionId: github_pr_comment
            params:
              person: keen
              message: Lovely. Let me take a look.
              
        github_pr_workflow_complete_success:
          do:
          - actionId: github_pr_approve
            params:
              person: keen
              message: Amazing, that will save us (meaning you) tons of work.
              
        github_pr_workflow_complete_failure:
          do:
          - actionId: github_pr_reject
            params:
              person: keen
              message: "Umm, something is not quite right, please make sure your output is in the following format: `first name` `last name`."

        github_pr_merged:
          do:
          - actionId: finish_step


githubActions:
  backend:
    testFile: "check.js"
    cmd: "bash ${testFile}"
