id: get_names
learningObjectives: 
- Reading through logs
hints:
- Check the logs for the users who accessed the system on June 16
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Mmmhh two users huh? What are the names of the users?"
        delay: 1500
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
          - - "cyrus"
            - "sean"
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "That's great, ${user.firstName}. That's all I needed for now." 
              delay: 1300
            - text: "Joe will take it from here." 
        - actionId: finish_step
        - actionId: bot_message
          params:
            person: lucca
            messages:
            - text: "Hey new guy! You're really good with this Bash thing"
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "I don't recognize these."
              delay: 2500
