id: get_names
learningObjectives: 
- Reading through logs
hints:
- Check the logs for the users who accessed the system on June 16
startFlow: 
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Mmmhh two users huh? What are the names of the users?"
        delay: 1000

trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
          - - "cyrus"
            - "sean"
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "That's great, ${user.firstName}. We're now one step closer to catching the bad guys." 
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "I don't think that's correct. Please check again"
              delay: 2500
